# Generated by Django 3.2.5 on 2021-07-27 17:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=40, null=True)),
                ('payment_type', models.CharField(max_length=40, null=True)),
                ('payment_status', models.CharField(max_length=40, null=True)),
                ('customer_name', models.CharField(max_length=20, null=True)),
                ('room_id', models.IntegerField(null=True)),
                ('customer_id', models.IntegerField(null=True)),
                ('room_type', models.CharField(max_length=40, null=True)),
                ('no_of_guests', models.IntegerField(max_length=20, null=True)),
                ('booking_reference', models.CharField(max_length=50, null=True)),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
                ('number_of_rooms', models.IntegerField()),
                ('booking_amount', models.FloatField(null=True)),
                ('booking_status', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=14)),
                ('address', models.CharField(max_length=500)),
                ('date_of_birth', models.DateField()),
                ('date_created', models.DateField(default=datetime.date(2021, 7, 27))),
                ('date_updated', models.DateField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, null=True)),
                ('booking_reference', models.CharField(max_length=100, null=True)),
                ('payment_status', models.CharField(max_length=20, null=True)),
                ('payment_type', models.CharField(max_length=40, null=True)),
                ('amount', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('date_of_payment', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_reference', models.CharField(max_length=100, null=True)),
                ('guest_name', models.CharField(max_length=100, null=True)),
                ('room_number', models.IntegerField()),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.IntegerField()),
                ('room_number', models.IntegerField()),
                ('room_type', models.CharField(max_length=20)),
                ('room_status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=14)),
                ('address', models.CharField(max_length=500)),
                ('date_of_birth', models.DateField()),
                ('date_created', models.DateField(default=datetime.date(2021, 7, 27))),
                ('date_updated', models.DateField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_reference', models.CharField(max_length=100, null=True)),
                ('room_number', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('balance', models.IntegerField(null=True)),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
                ('customer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='HMS.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Cleanup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleaner_id', models.IntegerField(null=True)),
                ('cleanup_date', models.DateTimeField()),
                ('comments', models.CharField(max_length=1000, null=True)),
                ('cleanup_reference', models.CharField(max_length=100, null=True)),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='HMS.rooms')),
            ],
        ),
        migrations.CreateModel(
            name='Cleaner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=14)),
                ('address', models.CharField(max_length=500)),
                ('date_of_birth', models.DateField()),
                ('date_created', models.DateField(default=datetime.date(2021, 7, 27))),
                ('date_updated', models.DateField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
