# Generated by Django 3.2.5 on 2021-10-09 05:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='cleaner',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='address',
        ),
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='cleaner',
            name='date_created',
            field=models.DateField(default=datetime.date(2021, 10, 8)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_created',
            field=models.DateField(default=datetime.date(2021, 10, 8)),
        ),
        migrations.AlterField(
            model_name='manager',
            name='date_created',
            field=models.DateField(default=datetime.date(2021, 10, 8)),
        ),
    ]
