# Generated by Django 3.2.5 on 2021-11-18 00:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HMS', '0002_auto_20211008_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='customer_id',
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_email',
            field=models.CharField(default=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_phone_number',
            field=models.CharField(default=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cleaner',
            name='date_created',
            field=models.DateField(default=datetime.date(2021, 11, 17)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_created',
            field=models.DateField(default=datetime.date(2021, 11, 17)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='manager',
            name='date_created',
            field=models.DateField(default=datetime.date(2021, 11, 17)),
        ),
    ]
