# Generated by Django 3.2.5 on 2022-01-15 06:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HMS', '0004_alter_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='no_of_guests',
        ),
        migrations.AlterField(
            model_name='cleaner',
            name='date_created',
            field=models.DateField(default=datetime.date(2022, 1, 14)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_created',
            field=models.DateField(default=datetime.date(2022, 1, 14)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='manager',
            name='date_created',
            field=models.DateField(default=datetime.date(2022, 1, 14)),
        ),
    ]
