# Generated by Django 3.2.5 on 2022-01-15 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HMS', '0005_auto_20220114_2210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='room_number',
            new_name='room_numbers',
        ),
    ]
