# Generated by Django 3.2.5 on 2022-01-15 18:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS', '0006_rename_room_number_guest_room_numbers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='customer',
        ),
        migrations.AlterField(
            model_name='cleaner',
            name='date_created',
            field=models.DateField(default=datetime.date(2022, 1, 15)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_created',
            field=models.DateField(default=datetime.date(2022, 1, 15)),
        ),
        migrations.AlterField(
            model_name='manager',
            name='date_created',
            field=models.DateField(default=datetime.date(2022, 1, 15)),
        ),
    ]
