# Generated by Django 3.2.5 on 2022-01-15 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HMS', '0007_auto_20220115_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cleanup',
            name='room_id',
        ),
        migrations.DeleteModel(
            name='Cleaner',
        ),
        migrations.DeleteModel(
            name='Cleanup',
        ),
    ]
